# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- releases/*
- features/*

pool:
  vmImage: 'ubuntu-latest'

container:
  image: julia
  endpoint: DockerHub

steps:

- task: CmdLine@2
  inputs:
    script: |
      julia --project=@. -e "import Pkg; Pkg.build()"
      julia --check-bounds=yes --project=@. -e "import Pkg; Pkg.test(; coverage=true)"
  displayName: 'Run Julia unit tests'
