name = "UncertaintyPropagation"
uuid = "49d00390-b664-4e50-8f10-002d92b2ec8a"
authors = ["Ryan Brown <ryan.brown@teledyne.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
